const blocks = [
  { type: 'heading', text: '학습 목표' },
  { type: 'list', items: [
    '컴퓨터 핵심 부품(CPU/RAM/디스크/I-O)의 역할을 설명한다',
    '운영체제(OS)가 하드웨어와 사용자/프로그램 사이에서 하는 일을 말로 풀어낸다',
    '사용자 공간과 커널 공간 분리의 이유를 이해한다',
  ]},
  { type: 'aside', text: "🧠 비유: 컴퓨터는 '레스토랑'. CPU=요리사, RAM=도마, 디스크=창고, 네트워크=전화/도로, OS=총괄 매니저." },
  { type: 'divider' },
  { type: 'heading', text: '컴퓨터의 핵심 부품(하드웨어)' },
  { type: 'list', items: [
    "CPU(중앙처리장치): 명령을 해석·실행하는 '두뇌'. 코어/스레드/클록이 성능의 큰 축.",
    "RAM(메모리): '작업대'. 당장 필요한 코드/데이터를 빠르게 담아둠. 전원 끄면 휘발.",
    "저장장치(HDD/SSD/NVMe): '창고'. 영구 저장. SSD는 빠르고 HDD는 용량 대비 저렴.",
    "I/O(키보드·마우스·디스플레이·네트워크): 외부와의 입력/출력 통로.",
    "버스/칩셋: 부품 간 데이터가 오가는 길목과 신호 규칙.",
  ]},
  { type: 'heading', text: 'CPU 자세히 보기' },
  { type: 'list', items: [
    '코어/스레드: 물리 코어와 하이퍼스레딩으로 동시 실행 성능 향상',
    '클록/터보: 기본/최대 동작 주파수. 발열·전력에 따라 가변',
    '캐시(L1/L2/L3): 가까운 고속 메모리로 지연을 줄임',
    '명령 집합(ISA): x86_64, ARM 등 아키텍처 차이',
    '가상화 지원: VT-x/AMD-V, 컨테이너와는 다른 개념(하드웨어 가상화)',
  ]},
  { type: 'heading', text: '메모리 계층과 가상 메모리' },
  { type: 'list', items: [
    '계층: 레지스터 → 캐시(L1/L2/L3) → RAM → 스토리지(가상 메모리 백업)',
    '페이지(일반 4KB): 메모리는 페이지 단위로 관리, 페이지 캐시/버퍼 캐시 활용',
    'NUMA: 소켓별 메모리 지연 차이, 서버에서 성능 영향',
    'OOM Killer: 메모리 부족 시 커널이 프로세스 종료로 시스템 보호',
  ]},
  { type: 'heading', text: '스왑(Swap) 이해하기' },
  { type: 'list', items: [
    '정의: RAM이 부족할 때 덜 자주 쓰는 페이지를 디스크(스왑 영역)로 밀어냄',
    '장점: 급한 상황에서 프로세스 종료(OOM) 대신 연명',
    '단점: 디스크는 RAM보다 매우 느려 체감 성능 저하',
    'swappiness: 커널이 스왑을 얼마나 적극적으로 쓰는지(0~100)',
    '형태: 스왑 파티션 또는 스왑 파일',
  ]},
  { type: 'heading', text: '스토리지: HDD vs SSD vs NVMe' },
  { type: 'list', items: [
    'HDD: 회전 디스크+헤드(기계식). 지연이 크지만 대용량 저렴',
    'SATA SSD: 플래시 기반. 무작위 I/O 성능이 HDD 대비 비약적',
    'NVMe SSD: PCIe 인터페이스로 더 높은 대역폭·낮은 지연',
    '내구도(TBW)와 TRIM: 플래시 수명·성능 유지에 중요',
    '파일시스템·마운트 옵션: 성능·내구성에 영향(noatime 등)',
  ]},
  { type: 'heading', text: '파일시스템 한눈에' },
  { type: 'list', items: [
    'EXT4: 범용 안정, 저널링 지원',
    'XFS: 대용량/병렬 워크로드 강점',
    'Btrfs: 스냅샷/서브볼륨/체크섬 등 현대적 기능',
    '마운트 포인트: 디렉토리 트리에 장치를 붙이는 과정(/etc/fstab 자동 마운트)',
  ]},
  { type: 'heading', text: 'OS의 자리와 핵심 역할' },
  { type: 'list', items: [
    '자원 관리: CPU·메모리·스토리지·네트워크를 공정하고 효율적으로 배분',
    '추상화: 하드웨어를 파일/프로세스/소켓 같은 개념으로 감싸 사용을 단순화',
    '보호/격리: 권한 모델과 메모리 보호로 안정성·보안 확보',
    '진입점: 시스템 콜 인터페이스로 프로그램 요청을 안전하게 처리',
  ]},
  { type: 'heading', text: 'OS 내부 한걸음 더' },
  { type: 'list', items: [
    '스케줄러(CFS 등): 태스크에 CPU 시간을 배분',
    '가상 메모리: 페이지 테이블/페이지 폴트/페이지 캐시',
    '블록 I/O: 요청 병합·스케줄링, 버퍼/페이지 캐시와 연동',
    'VFS/드라이버: 통일된 파일 인터페이스와 하드웨어 드라이버 계층',
    '인터럽트/컨텍스트 스위칭: 하드웨어 이벤트 처리와 실행 전환',
  ]},
  { type: 'heading', text: '사용자 공간과 커널 공간' },
  { type: 'paragraph', text: '일반 앱은 사용자 공간에서 동작하며, 특권이 필요한 작업은 시스템 콜로 커널에 위임합니다. 커널은 높은 권한으로 장치 제어·자원 관리·보호 기능을 수행합니다.' },
  { type: 'heading', text: '시스템 콜 흐름(간단 요약)' },
  { type: 'list', items: [
    '1) 앱이 read/write/open 등 시스템 콜을 호출',
    '2) 트랩(예외) 발생 → 커널 모드 전환',
    '3) 커널이 요청을 검사·실행(권한/자원/장치 접근)',
    '4) 결과를 돌려주고 사용자 모드로 복귀',
  ]},
  { type: 'divider' },
  { type: 'heading', text: '빠른 확인(Hands-on)' },
  { type: 'list', items: [
    'CPU: lscpu | grep -E "Model name|CPU\\(s\\)|Thread|Core|MHz|L3"',
    '메모리: free -h; vmstat 1 5',
    '스왑: swapon --show; cat /proc/meminfo | grep -i swap',
    '디스크: lsblk -o NAME,ROTA,TYPE,SIZE,MOUNTPOINT,MODEL; df -hT',
    '파일시스템·마운트: lsblk -f; findmnt -t ext4,xfs,btrfs',
    '커널/아키: uname -srm',
  ]},
  { type: 'heading', text: '체크리스트·퀴즈' },
  { type: 'list', items: [
    'CPU·RAM·스토리지·I/O 각각의 역할을 한 문장으로 요약하라',
    'OS가 제공하는 “추상화”의 예를 2가지 들어라',
    '사용자/커널 공간을 분리하는 이유는 무엇인가',
  ]},
  { type: 'heading', text: '요약' },
  { type: 'paragraph', text: 'OS는 하드웨어 위에 서서 자원을 관리하고, 복잡성을 감춘 친숙한 추상과 보호 장치를 제공합니다. 이 덕분에 우리는 파일/프로세스 관점에서 시스템을 다룰 수 있습니다.' },
]

export default blocks as any

